export enum ActionTypes {
  ARTICLES_REQUEST_START,
  ARTICLES_REQUEST_FAIL,
  ARTICLES_GET_SUCCESS,

  DETAIL_ARTICLE_REQUEST_START,
  DETAIL_ARTICLE_REQUEST_FAIL,
  DETAIL_ARTICLE_GET_SUCCESS,
  DETAIL_ARTICLE_REMOVE,
}
